import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)
const ALERT_EMAIL = process.env.ALERT_EMAIL || 'abhay@example.com'

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' })
  }

  const { type, url, userAgent, timestamp, error } = req.body

  try {
    const subject = `🚨 Wedding Site Error: ${type.toUpperCase()}`
    const html = `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px;">
        <h2 style="color: #dc2626; margin-bottom: 16px;">Wedding Website Error Alert</h2>
        <table style="width: 100%; border-collapse: collapse; margin-bottom: 24px;">
          <tr>
            <td style="padding: 8px 0; font-weight: 600; color: #374151;">Error Type</td>
            <td style="padding: 8px 0; color: #1f2937;">${type}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; font-weight: 600; color: #374151;">URL</td>
            <td style="padding: 8px 0; color: #1f2937; word-break: break-all;"><a href="${url}" style="color: #C9A96E;">${url}</a></td>
          </tr>
          <tr>
            <td style="padding: 8px 0; font-weight: 600; color: #374151;">Timestamp</td>
            <td style="padding: 8px 0; color: #1f2937;">${timestamp}</td>
          </tr>
          <tr>
            <td style="padding: 8px 0; font-weight: 600; color: #374151;">User Agent</td>
            <td style="padding: 8px 0; color: #1f2937; word-break: break-all;">${userAgent}</td>
          </tr>
          ${error ? `
          <tr>
            <td style="padding: 8px 0; font-weight: 600; color: #374151;">Error Details</td>
            <td style="padding: 8px 0; color: #1f2937; white-space: pre-wrap;">${error}</td>
          </tr>
          ` : ''}
        </table>
        <p style="color: #6b7280; font-size: 14px;">This alert was automatically generated by the wedding website error monitoring.</p>
      </div>
    `

    await resend.emails.send({
      from: 'Wedding Site Alerts <alerts@abhayandrebecca.com>',
      to: ALERT_EMAIL,
      subject,
      html,
    })

    return res.status(200).json({ success: true })
  } catch (err) {
    console.error('Failed to send error alert email:', err)
    return res.status(500).json({ error: 'Failed to send alert' })
  }
}